/*
 * Generated by gdbus-codegen 2.32.4. DO NOT EDIT.
 *
 * The license of this code is the same as for the source it was derived from.
 */

#ifdef HAVE_CONFIG_H
#  include "config.h"
#endif

#include "hs-dbus-manager.h"

#include <string.h>
#ifdef G_OS_UNIX
#  include <gio/gunixfdlist.h>
#endif

typedef struct
{
  GDBusArgInfo parent_struct;
  gboolean use_gvariant;
} _ExtendedGDBusArgInfo;

typedef struct
{
  GDBusMethodInfo parent_struct;
  const gchar *signal_name;
  gboolean pass_fdlist;
} _ExtendedGDBusMethodInfo;

typedef struct
{
  GDBusSignalInfo parent_struct;
  const gchar *signal_name;
} _ExtendedGDBusSignalInfo;

typedef struct
{
  GDBusPropertyInfo parent_struct;
  const gchar *hyphen_name;
  gboolean use_gvariant;
} _ExtendedGDBusPropertyInfo;

typedef struct
{
  GDBusInterfaceInfo parent_struct;
  const gchar *hyphen_name;
} _ExtendedGDBusInterfaceInfo;

typedef struct
{
  const _ExtendedGDBusPropertyInfo *info;
  guint prop_id;
  GValue orig_value; /* the value before the change */
} ChangedProperty;

static void
_changed_property_free (ChangedProperty *data)
{
  g_value_unset (&data->orig_value);
  g_free (data);
}

static gboolean
_g_strv_equal0 (gchar **a, gchar **b)
{
  gboolean ret = FALSE;
  guint n;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  if (g_strv_length (a) != g_strv_length (b))
    goto out;
  for (n = 0; a[n] != NULL; n++)
    if (g_strcmp0 (a[n], b[n]) != 0)
      goto out;
  ret = TRUE;
out:
  return ret;
}

static gboolean
_g_variant_equal0 (GVariant *a, GVariant *b)
{
  gboolean ret = FALSE;
  if (a == NULL && b == NULL)
    {
      ret = TRUE;
      goto out;
    }
  if (a == NULL || b == NULL)
    goto out;
  ret = g_variant_equal (a, b);
out:
  return ret;
}

G_GNUC_UNUSED static gboolean
_g_value_equal (const GValue *a, const GValue *b)
{
  gboolean ret = FALSE;
  g_assert (G_VALUE_TYPE (a) == G_VALUE_TYPE (b));
  switch (G_VALUE_TYPE (a))
    {
      case G_TYPE_BOOLEAN:
        ret = (g_value_get_boolean (a) == g_value_get_boolean (b));
        break;
      case G_TYPE_UCHAR:
        ret = (g_value_get_uchar (a) == g_value_get_uchar (b));
        break;
      case G_TYPE_INT:
        ret = (g_value_get_int (a) == g_value_get_int (b));
        break;
      case G_TYPE_UINT:
        ret = (g_value_get_uint (a) == g_value_get_uint (b));
        break;
      case G_TYPE_INT64:
        ret = (g_value_get_int64 (a) == g_value_get_int64 (b));
        break;
      case G_TYPE_UINT64:
        ret = (g_value_get_uint64 (a) == g_value_get_uint64 (b));
        break;
      case G_TYPE_DOUBLE:
        {
          /* Avoid -Wfloat-equal warnings by doing a direct bit compare */
          gdouble da = g_value_get_double (a);
          gdouble db = g_value_get_double (b);
          ret = memcmp (&da, &db, sizeof (gdouble)) == 0;
        }
        break;
      case G_TYPE_STRING:
        ret = (g_strcmp0 (g_value_get_string (a), g_value_get_string (b)) == 0);
        break;
      case G_TYPE_VARIANT:
        ret = _g_variant_equal0 (g_value_get_variant (a), g_value_get_variant (b));
        break;
      default:
        if (G_VALUE_TYPE (a) == G_TYPE_STRV)
          ret = _g_strv_equal0 (g_value_get_boxed (a), g_value_get_boxed (b));
        else
          g_critical ("_g_value_equal() does not handle type %s", g_type_name (G_VALUE_TYPE (a)));
        break;
    }
  return ret;
}

/* ------------------------------------------------------------------------
 * Code for interface org.home.hsession.Manager.Power
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:HsPower
 * @title: HsPower
 * @short_description: Generated C code for the org.home.hsession.Manager.Power D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.home.hsession.Manager.Power ---- */

static const _ExtendedGDBusMethodInfo _hs_power_method_info_halt =
{
  {
    -1,
    "Halt",
    NULL,
    NULL,
    NULL
  },
  "handle-halt",
  FALSE
};

static const _ExtendedGDBusMethodInfo _hs_power_method_info_restart =
{
  {
    -1,
    "Restart",
    NULL,
    NULL,
    NULL
  },
  "handle-restart",
  FALSE
};

static const _ExtendedGDBusMethodInfo _hs_power_method_info_suspend =
{
  {
    -1,
    "Suspend",
    NULL,
    NULL,
    NULL
  },
  "handle-suspend",
  FALSE
};

static const _ExtendedGDBusMethodInfo _hs_power_method_info_hibernate =
{
  {
    -1,
    "Hibernate",
    NULL,
    NULL,
    NULL
  },
  "handle-hibernate",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _hs_power_method_info_pointers[] =
{
  &_hs_power_method_info_halt,
  &_hs_power_method_info_restart,
  &_hs_power_method_info_suspend,
  &_hs_power_method_info_hibernate,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _hs_power_interface_info =
{
  {
    -1,
    "org.home.hsession.Manager.Power",
    (GDBusMethodInfo **) &_hs_power_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "power",
};


/**
 * hs_power_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
hs_power_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_hs_power_interface_info;
}

/**
 * hs_power_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #HsPower interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
hs_power_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * HsPower:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>.
 */

/**
 * HsPowerIface:
 * @parent_iface: The parent interface.
 * @handle_halt: Handler for the #HsPower::handle-halt signal.
 * @handle_hibernate: Handler for the #HsPower::handle-hibernate signal.
 * @handle_restart: Handler for the #HsPower::handle-restart signal.
 * @handle_suspend: Handler for the #HsPower::handle-suspend signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>.
 */

static void
hs_power_default_init (HsPowerIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * HsPower::handle-halt:
   * @object: A #HsPower.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Halt">Halt()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call hs_power_complete_halt() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-halt",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (HsPowerIface, handle_halt),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * HsPower::handle-restart:
   * @object: A #HsPower.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Restart">Restart()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call hs_power_complete_restart() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-restart",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (HsPowerIface, handle_restart),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * HsPower::handle-suspend:
   * @object: A #HsPower.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Suspend">Suspend()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call hs_power_complete_suspend() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-suspend",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (HsPowerIface, handle_suspend),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

  /**
   * HsPower::handle-hibernate:
   * @object: A #HsPower.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Hibernate">Hibernate()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call hs_power_complete_hibernate() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-hibernate",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (HsPowerIface, handle_hibernate),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

}

typedef HsPowerIface HsPowerInterface;
G_DEFINE_INTERFACE (HsPower, hs_power, G_TYPE_OBJECT);

/**
 * hs_power_call_halt:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Halt">Halt()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_call_halt_finish() to get the result of the operation.
 *
 * See hs_power_call_halt_sync() for the synchronous, blocking version of this method.
 */
void
hs_power_call_halt (
    HsPower *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Halt",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * hs_power_call_halt_finish:
 * @proxy: A #HsPowerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_call_halt().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with hs_power_call_halt().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_halt_finish (
    HsPower *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_halt_sync:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Halt">Halt()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See hs_power_call_halt() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_halt_sync (
    HsPower *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Halt",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_restart:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Restart">Restart()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_call_restart_finish() to get the result of the operation.
 *
 * See hs_power_call_restart_sync() for the synchronous, blocking version of this method.
 */
void
hs_power_call_restart (
    HsPower *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Restart",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * hs_power_call_restart_finish:
 * @proxy: A #HsPowerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_call_restart().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with hs_power_call_restart().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_restart_finish (
    HsPower *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_restart_sync:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Restart">Restart()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See hs_power_call_restart() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_restart_sync (
    HsPower *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Restart",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_suspend:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Suspend">Suspend()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_call_suspend_finish() to get the result of the operation.
 *
 * See hs_power_call_suspend_sync() for the synchronous, blocking version of this method.
 */
void
hs_power_call_suspend (
    HsPower *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Suspend",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * hs_power_call_suspend_finish:
 * @proxy: A #HsPowerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_call_suspend().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with hs_power_call_suspend().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_suspend_finish (
    HsPower *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_suspend_sync:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Suspend">Suspend()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See hs_power_call_suspend() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_suspend_sync (
    HsPower *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Suspend",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_hibernate:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Hibernate">Hibernate()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_call_hibernate_finish() to get the result of the operation.
 *
 * See hs_power_call_hibernate_sync() for the synchronous, blocking version of this method.
 */
void
hs_power_call_hibernate (
    HsPower *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Hibernate",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * hs_power_call_hibernate_finish:
 * @proxy: A #HsPowerProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_call_hibernate().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with hs_power_call_hibernate().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_hibernate_finish (
    HsPower *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_call_hibernate_sync:
 * @proxy: A #HsPowerProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Hibernate">Hibernate()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See hs_power_call_hibernate() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_power_call_hibernate_sync (
    HsPower *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Hibernate",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_power_complete_halt:
 * @object: A #HsPower.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Halt">Halt()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
hs_power_complete_halt (
    HsPower *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * hs_power_complete_restart:
 * @object: A #HsPower.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Restart">Restart()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
hs_power_complete_restart (
    HsPower *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * hs_power_complete_suspend:
 * @object: A #HsPower.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Suspend">Suspend()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
hs_power_complete_suspend (
    HsPower *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/**
 * hs_power_complete_hibernate:
 * @object: A #HsPower.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-home-hsession-Manager-Power.Hibernate">Hibernate()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
hs_power_complete_hibernate (
    HsPower *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * HsPowerProxy:
 *
 * The #HsPowerProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsPowerProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsPowerProxy.
 */

struct _HsPowerProxyPrivate
{
  GData *qdata;
};

static void hs_power_proxy_iface_init (HsPowerIface *iface);

G_DEFINE_TYPE_WITH_CODE (HsPowerProxy, hs_power_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_POWER, hs_power_proxy_iface_init));

static void
hs_power_proxy_finalize (GObject *object)
{
  HsPowerProxy *proxy = HS_POWER_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (hs_power_proxy_parent_class)->finalize (object);
}

static void
hs_power_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
hs_power_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
hs_power_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_hs_power_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], HS_TYPE_POWER);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, HS_TYPE_POWER);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
hs_power_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  HsPowerProxy *proxy = HS_POWER_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_power_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_power_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
hs_power_proxy_init (HsPowerProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, HS_TYPE_POWER_PROXY, HsPowerProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), hs_power_interface_info ());
}

static void
hs_power_proxy_class_init (HsPowerProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (HsPowerProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = hs_power_proxy_finalize;
  gobject_class->get_property = hs_power_proxy_get_property;
  gobject_class->set_property = hs_power_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = hs_power_proxy_g_signal;
  proxy_class->g_properties_changed = hs_power_proxy_g_properties_changed;

}

static void
hs_power_proxy_iface_init (HsPowerIface *iface)
{
}

/**
 * hs_power_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_proxy_new_finish() to get the result of the operation.
 *
 * See hs_power_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_power_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (HS_TYPE_POWER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Power", NULL);
}

/**
 * hs_power_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_power_proxy_new().
 *
 * Returns: (transfer full) (type HsPowerProxy): The constructed proxy object or %NULL if @error is set.
 */
HsPower *
hs_power_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return HS_POWER (ret);
  else
    return NULL;
}

/**
 * hs_power_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_power_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsPowerProxy): The constructed proxy object or %NULL if @error is set.
 */
HsPower *
hs_power_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_POWER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Power", NULL);
  if (ret != NULL)
    return HS_POWER (ret);
  else
    return NULL;
}


/**
 * hs_power_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like hs_power_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_power_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See hs_power_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_power_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (HS_TYPE_POWER_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Power", NULL);
}

/**
 * hs_power_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_power_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_power_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type HsPowerProxy): The constructed proxy object or %NULL if @error is set.
 */
HsPower *
hs_power_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return HS_POWER (ret);
  else
    return NULL;
}

/**
 * hs_power_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like hs_power_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_power_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsPowerProxy): The constructed proxy object or %NULL if @error is set.
 */
HsPower *
hs_power_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_POWER_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Power", NULL);
  if (ret != NULL)
    return HS_POWER (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * HsPowerSkeleton:
 *
 * The #HsPowerSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsPowerSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsPowerSkeleton.
 */

struct _HsPowerSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_hs_power_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  HsPowerSkeleton *skeleton = HS_POWER_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], HS_TYPE_POWER);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, HS_TYPE_POWER);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_hs_power_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  HsPowerSkeleton *skeleton = HS_POWER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_power_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_hs_power_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  HsPowerSkeleton *skeleton = HS_POWER_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_power_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _hs_power_skeleton_vtable =
{
  _hs_power_skeleton_handle_method_call,
  _hs_power_skeleton_handle_get_property,
  _hs_power_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
hs_power_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return hs_power_interface_info ();
}

static GDBusInterfaceVTable *
hs_power_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_hs_power_skeleton_vtable;
}

static GVariant *
hs_power_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  HsPowerSkeleton *skeleton = HS_POWER_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_hs_power_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _hs_power_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _hs_power_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _hs_power_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.home.hsession.Manager.Power", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
hs_power_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void hs_power_skeleton_iface_init (HsPowerIface *iface);
G_DEFINE_TYPE_WITH_CODE (HsPowerSkeleton, hs_power_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_POWER, hs_power_skeleton_iface_init));

static void
hs_power_skeleton_finalize (GObject *object)
{
  HsPowerSkeleton *skeleton = HS_POWER_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (hs_power_skeleton_parent_class)->finalize (object);
}

static void
hs_power_skeleton_init (HsPowerSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, HS_TYPE_POWER_SKELETON, HsPowerSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
hs_power_skeleton_class_init (HsPowerSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (HsPowerSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = hs_power_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = hs_power_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = hs_power_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = hs_power_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = hs_power_skeleton_dbus_interface_get_vtable;
}

static void
hs_power_skeleton_iface_init (HsPowerIface *iface)
{
}

/**
 * hs_power_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>.
 *
 * Returns: (transfer full) (type HsPowerSkeleton): The skeleton object.
 */
HsPower *
hs_power_skeleton_new (void)
{
  return HS_POWER (g_object_new (HS_TYPE_POWER_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for interface org.home.hsession.Manager.Session
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:HsSession
 * @title: HsSession
 * @short_description: Generated C code for the org.home.hsession.Manager.Session D-Bus interface
 *
 * This section contains code for working with the <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link> D-Bus interface in C.
 */

/* ---- Introspection data for org.home.hsession.Manager.Session ---- */

static const _ExtendedGDBusMethodInfo _hs_session_method_info_logout =
{
  {
    -1,
    "Logout",
    NULL,
    NULL,
    NULL
  },
  "handle-logout",
  FALSE
};

static const _ExtendedGDBusMethodInfo * const _hs_session_method_info_pointers[] =
{
  &_hs_session_method_info_logout,
  NULL
};

static const _ExtendedGDBusInterfaceInfo _hs_session_interface_info =
{
  {
    -1,
    "org.home.hsession.Manager.Session",
    (GDBusMethodInfo **) &_hs_session_method_info_pointers,
    NULL,
    NULL,
    NULL
  },
  "session",
};


/**
 * hs_session_interface_info:
 *
 * Gets a machine-readable description of the <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link> D-Bus interface.
 *
 * Returns: (transfer none): A #GDBusInterfaceInfo. Do not free.
 */
GDBusInterfaceInfo *
hs_session_interface_info (void)
{
  return (GDBusInterfaceInfo *) &_hs_session_interface_info;
}

/**
 * hs_session_override_properties:
 * @klass: The class structure for a #GObject<!-- -->-derived class.
 * @property_id_begin: The property id to assign to the first overridden property.
 *
 * Overrides all #GObject properties in the #HsSession interface for a concrete class.
 * The properties are overridden in the order they are defined.
 *
 * Returns: The last property id.
 */
guint
hs_session_override_properties (GObjectClass *klass, guint property_id_begin)
{
  return property_id_begin - 1;
}



/**
 * HsSession:
 *
 * Abstract interface type for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>.
 */

/**
 * HsSessionIface:
 * @parent_iface: The parent interface.
 * @handle_logout: Handler for the #HsSession::handle-logout signal.
 *
 * Virtual table for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>.
 */

static void
hs_session_default_init (HsSessionIface *iface)
{
  /* GObject signals for incoming D-Bus method calls: */
  /**
   * HsSession::handle-logout:
   * @object: A #HsSession.
   * @invocation: A #GDBusMethodInvocation.
   *
   * Signal emitted when a remote caller is invoking the <link linkend="gdbus-method-org-home-hsession-Manager-Session.Logout">Logout()</link> D-Bus method.
   *
   * If a signal handler returns %TRUE, it means the signal handler will handle the invocation (e.g. take a reference to @invocation and eventually call hs_session_complete_logout() or e.g. g_dbus_method_invocation_return_error() on it) and no order signal handlers will run. If no signal handler handles the invocation, the %G_DBUS_ERROR_UNKNOWN_METHOD error is returned.
   *
   * Returns: %TRUE if the invocation was handled, %FALSE to let other signal handlers run.
   */
  g_signal_new ("handle-logout",
    G_TYPE_FROM_INTERFACE (iface),
    G_SIGNAL_RUN_LAST,
    G_STRUCT_OFFSET (HsSessionIface, handle_logout),
    g_signal_accumulator_true_handled,
    NULL,
    g_cclosure_marshal_generic,
    G_TYPE_BOOLEAN,
    1,
    G_TYPE_DBUS_METHOD_INVOCATION);

}

typedef HsSessionIface HsSessionInterface;
G_DEFINE_INTERFACE (HsSession, hs_session, G_TYPE_OBJECT);

/**
 * hs_session_call_logout:
 * @proxy: A #HsSessionProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied or %NULL.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Session.Logout">Logout()</link> D-Bus method on @proxy.
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_session_call_logout_finish() to get the result of the operation.
 *
 * See hs_session_call_logout_sync() for the synchronous, blocking version of this method.
 */
void
hs_session_call_logout (
    HsSession *proxy,
    GCancellable *cancellable,
    GAsyncReadyCallback callback,
    gpointer user_data)
{
  g_dbus_proxy_call (G_DBUS_PROXY (proxy),
    "Logout",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    callback,
    user_data);
}

/**
 * hs_session_call_logout_finish:
 * @proxy: A #HsSessionProxy.
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_session_call_logout().
 * @error: Return location for error or %NULL.
 *
 * Finishes an operation started with hs_session_call_logout().
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_session_call_logout_finish (
    HsSession *proxy,
    GAsyncResult *res,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_finish (G_DBUS_PROXY (proxy), res, error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_session_call_logout_sync:
 * @proxy: A #HsSessionProxy.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL.
 *
 * Synchronously invokes the <link linkend="gdbus-method-org-home-hsession-Manager-Session.Logout">Logout()</link> D-Bus method on @proxy. The calling thread is blocked until a reply is received.
 *
 * See hs_session_call_logout() for the asynchronous version of this method.
 *
 * Returns: (skip): %TRUE if the call succeded, %FALSE if @error is set.
 */
gboolean
hs_session_call_logout_sync (
    HsSession *proxy,
    GCancellable *cancellable,
    GError **error)
{
  GVariant *_ret;
  _ret = g_dbus_proxy_call_sync (G_DBUS_PROXY (proxy),
    "Logout",
    g_variant_new ("()"),
    G_DBUS_CALL_FLAGS_NONE,
    -1,
    cancellable,
    error);
  if (_ret == NULL)
    goto _out;
  g_variant_get (_ret,
                 "()");
  g_variant_unref (_ret);
_out:
  return _ret != NULL;
}

/**
 * hs_session_complete_logout:
 * @object: A #HsSession.
 * @invocation: (transfer full): A #GDBusMethodInvocation.
 *
 * Helper function used in service implementations to finish handling invocations of the <link linkend="gdbus-method-org-home-hsession-Manager-Session.Logout">Logout()</link> D-Bus method. If you instead want to finish handling an invocation by returning an error, use g_dbus_method_invocation_return_error() or similar.
 *
 * This method will free @invocation, you cannot use it afterwards.
 */
void
hs_session_complete_logout (
    HsSession *object,
    GDBusMethodInvocation *invocation)
{
  g_dbus_method_invocation_return_value (invocation,
    g_variant_new ("()"));
}

/* ------------------------------------------------------------------------ */

/**
 * HsSessionProxy:
 *
 * The #HsSessionProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsSessionProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsSessionProxy.
 */

struct _HsSessionProxyPrivate
{
  GData *qdata;
};

static void hs_session_proxy_iface_init (HsSessionIface *iface);

G_DEFINE_TYPE_WITH_CODE (HsSessionProxy, hs_session_proxy, G_TYPE_DBUS_PROXY,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_SESSION, hs_session_proxy_iface_init));

static void
hs_session_proxy_finalize (GObject *object)
{
  HsSessionProxy *proxy = HS_SESSION_PROXY (object);
  g_datalist_clear (&proxy->priv->qdata);
  G_OBJECT_CLASS (hs_session_proxy_parent_class)->finalize (object);
}

static void
hs_session_proxy_get_property (GObject      *object,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
}

static void
hs_session_proxy_set_property (GObject      *object,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
}

static void
hs_session_proxy_g_signal (GDBusProxy *proxy,
  const gchar *sender_name,
  const gchar *signal_name,
  GVariant *parameters)
{
  _ExtendedGDBusSignalInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint n;
  guint signal_id;
  info = (_ExtendedGDBusSignalInfo *) g_dbus_interface_info_lookup_signal ((GDBusInterfaceInfo *) &_hs_session_interface_info, signal_name);
  if (info == NULL)
    return;
  num_params = g_variant_n_children (parameters);
  paramv = g_new0 (GValue, num_params + 1);
  g_value_init (&paramv[0], HS_TYPE_SESSION);
  g_value_set_object (&paramv[0], proxy);
  g_variant_iter_init (&iter, parameters);
  n = 1;
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.args[n - 1];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, HS_TYPE_SESSION);
  g_signal_emitv (paramv, signal_id, 0, NULL);
  for (n = 0; n < num_params + 1; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static void
hs_session_proxy_g_properties_changed (GDBusProxy *_proxy,
  GVariant *changed_properties,
  const gchar *const *invalidated_properties)
{
  HsSessionProxy *proxy = HS_SESSION_PROXY (_proxy);
  guint n;
  const gchar *key;
  GVariantIter *iter;
  _ExtendedGDBusPropertyInfo *info;
  g_variant_get (changed_properties, "a{sv}", &iter);
  while (g_variant_iter_next (iter, "{&sv}", &key, NULL))
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_session_interface_info, key);
      g_datalist_remove_data (&proxy->priv->qdata, key);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
  g_variant_iter_free (iter);
  for (n = 0; invalidated_properties[n] != NULL; n++)
    {
      info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_session_interface_info, invalidated_properties[n]);
      g_datalist_remove_data (&proxy->priv->qdata, invalidated_properties[n]);
      if (info != NULL)
        g_object_notify (G_OBJECT (proxy), info->hyphen_name);
    }
}

static void
hs_session_proxy_init (HsSessionProxy *proxy)
{
  proxy->priv = G_TYPE_INSTANCE_GET_PRIVATE (proxy, HS_TYPE_SESSION_PROXY, HsSessionProxyPrivate);
  g_dbus_proxy_set_interface_info (G_DBUS_PROXY (proxy), hs_session_interface_info ());
}

static void
hs_session_proxy_class_init (HsSessionProxyClass *klass)
{
  GObjectClass *gobject_class;
  GDBusProxyClass *proxy_class;

  g_type_class_add_private (klass, sizeof (HsSessionProxyPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize     = hs_session_proxy_finalize;
  gobject_class->get_property = hs_session_proxy_get_property;
  gobject_class->set_property = hs_session_proxy_set_property;

  proxy_class = G_DBUS_PROXY_CLASS (klass);
  proxy_class->g_signal = hs_session_proxy_g_signal;
  proxy_class->g_properties_changed = hs_session_proxy_g_properties_changed;

}

static void
hs_session_proxy_iface_init (HsSessionIface *iface)
{
}

/**
 * hs_session_proxy_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>. See g_dbus_proxy_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_session_proxy_new_finish() to get the result of the operation.
 *
 * See hs_session_proxy_new_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_session_proxy_new (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (HS_TYPE_SESSION_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Session", NULL);
}

/**
 * hs_session_proxy_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_session_proxy_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_session_proxy_new().
 *
 * Returns: (transfer full) (type HsSessionProxy): The constructed proxy object or %NULL if @error is set.
 */
HsSession *
hs_session_proxy_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return HS_SESSION (ret);
  else
    return NULL;
}

/**
 * hs_session_proxy_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates a proxy for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>. See g_dbus_proxy_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_session_proxy_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsSessionProxy): The constructed proxy object or %NULL if @error is set.
 */
HsSession *
hs_session_proxy_new_sync (
    GDBusConnection     *connection,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_SESSION_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-connection", connection, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Session", NULL);
  if (ret != NULL)
    return HS_SESSION (ret);
  else
    return NULL;
}


/**
 * hs_session_proxy_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like hs_session_proxy_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_session_proxy_new_for_bus_finish() to get the result of the operation.
 *
 * See hs_session_proxy_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_session_proxy_new_for_bus (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GAsyncReadyCallback  callback,
    gpointer             user_data)
{
  g_async_initable_new_async (HS_TYPE_SESSION_PROXY, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Session", NULL);
}

/**
 * hs_session_proxy_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_session_proxy_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_session_proxy_new_for_bus().
 *
 * Returns: (transfer full) (type HsSessionProxy): The constructed proxy object or %NULL if @error is set.
 */
HsSession *
hs_session_proxy_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return HS_SESSION (ret);
  else
    return NULL;
}

/**
 * hs_session_proxy_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusProxyFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like hs_session_proxy_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_session_proxy_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsSessionProxy): The constructed proxy object or %NULL if @error is set.
 */
HsSession *
hs_session_proxy_new_for_bus_sync (
    GBusType             bus_type,
    GDBusProxyFlags      flags,
    const gchar         *name,
    const gchar         *object_path,
    GCancellable        *cancellable,
    GError             **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_SESSION_PROXY, cancellable, error, "g-flags", flags, "g-name", name, "g-bus-type", bus_type, "g-object-path", object_path, "g-interface-name", "org.home.hsession.Manager.Session", NULL);
  if (ret != NULL)
    return HS_SESSION (ret);
  else
    return NULL;
}


/* ------------------------------------------------------------------------ */

/**
 * HsSessionSkeleton:
 *
 * The #HsSessionSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsSessionSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsSessionSkeleton.
 */

struct _HsSessionSkeletonPrivate
{
  GValue *properties;
  GList *changed_properties;
  GSource *changed_properties_idle_source;
  GMainContext *context;
  GMutex lock;
};

static void
_hs_session_skeleton_handle_method_call (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *method_name,
  GVariant *parameters,
  GDBusMethodInvocation *invocation,
  gpointer user_data)
{
  HsSessionSkeleton *skeleton = HS_SESSION_SKELETON (user_data);
  _ExtendedGDBusMethodInfo *info;
  GVariantIter iter;
  GVariant *child;
  GValue *paramv;
  guint num_params;
  guint num_extra;
  guint n;
  guint signal_id;
  GValue return_value = G_VALUE_INIT;
  info = (_ExtendedGDBusMethodInfo *) g_dbus_method_invocation_get_method_info (invocation);
  g_assert (info != NULL);
  num_params = g_variant_n_children (parameters);
  num_extra = info->pass_fdlist ? 3 : 2;  paramv = g_new0 (GValue, num_params + num_extra);
  n = 0;
  g_value_init (&paramv[n], HS_TYPE_SESSION);
  g_value_set_object (&paramv[n++], skeleton);
  g_value_init (&paramv[n], G_TYPE_DBUS_METHOD_INVOCATION);
  g_value_set_object (&paramv[n++], invocation);
  if (info->pass_fdlist)
    {
#ifdef G_OS_UNIX
      g_value_init (&paramv[n], G_TYPE_UNIX_FD_LIST);
      g_value_set_object (&paramv[n++], g_dbus_message_get_unix_fd_list (g_dbus_method_invocation_get_message (invocation)));
#else
      g_assert_not_reached ();
#endif
    }
  g_variant_iter_init (&iter, parameters);
  while ((child = g_variant_iter_next_value (&iter)) != NULL)
    {
      _ExtendedGDBusArgInfo *arg_info = (_ExtendedGDBusArgInfo *) info->parent_struct.in_args[n - num_extra];
      if (arg_info->use_gvariant)
        {
          g_value_init (&paramv[n], G_TYPE_VARIANT);
          g_value_set_variant (&paramv[n], child);
          n++;
        }
      else
        g_dbus_gvariant_to_gvalue (child, &paramv[n++]);
      g_variant_unref (child);
    }
  signal_id = g_signal_lookup (info->signal_name, HS_TYPE_SESSION);
  g_value_init (&return_value, G_TYPE_BOOLEAN);
  g_signal_emitv (paramv, signal_id, 0, &return_value);
  if (!g_value_get_boolean (&return_value))
    g_dbus_method_invocation_return_error (invocation, G_DBUS_ERROR, G_DBUS_ERROR_UNKNOWN_METHOD, "Method %s is not implemented on interface %s", method_name, interface_name);
  g_value_unset (&return_value);
  for (n = 0; n < num_params + num_extra; n++)
    g_value_unset (&paramv[n]);
  g_free (paramv);
}

static GVariant *
_hs_session_skeleton_handle_get_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GError **error,
  gpointer user_data)
{
  HsSessionSkeleton *skeleton = HS_SESSION_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  GVariant *ret;
  ret = NULL;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_session_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      g_value_init (&value, pspec->value_type);
      g_object_get_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      ret = g_dbus_gvalue_to_gvariant (&value, G_VARIANT_TYPE (info->parent_struct.signature));
      g_value_unset (&value);
    }
  return ret;
}

static gboolean
_hs_session_skeleton_handle_set_property (
  GDBusConnection *connection,
  const gchar *sender,
  const gchar *object_path,
  const gchar *interface_name,
  const gchar *property_name,
  GVariant *variant,
  GError **error,
  gpointer user_data)
{
  HsSessionSkeleton *skeleton = HS_SESSION_SKELETON (user_data);
  GValue value = G_VALUE_INIT;
  GParamSpec *pspec;
  _ExtendedGDBusPropertyInfo *info;
  gboolean ret;
  ret = FALSE;
  info = (_ExtendedGDBusPropertyInfo *) g_dbus_interface_info_lookup_property ((GDBusInterfaceInfo *) &_hs_session_interface_info, property_name);
  g_assert (info != NULL);
  pspec = g_object_class_find_property (G_OBJECT_GET_CLASS (skeleton), info->hyphen_name);
  if (pspec == NULL)
    {
      g_set_error (error, G_DBUS_ERROR, G_DBUS_ERROR_INVALID_ARGS, "No property with name %s", property_name);
    }
  else
    {
      if (info->use_gvariant)
        g_value_set_variant (&value, variant);
      else
        g_dbus_gvariant_to_gvalue (variant, &value);
      g_object_set_property (G_OBJECT (skeleton), info->hyphen_name, &value);
      g_value_unset (&value);
      ret = TRUE;
    }
  return ret;
}

static const GDBusInterfaceVTable _hs_session_skeleton_vtable =
{
  _hs_session_skeleton_handle_method_call,
  _hs_session_skeleton_handle_get_property,
  _hs_session_skeleton_handle_set_property
};

static GDBusInterfaceInfo *
hs_session_skeleton_dbus_interface_get_info (GDBusInterfaceSkeleton *skeleton)
{
  return hs_session_interface_info ();
}

static GDBusInterfaceVTable *
hs_session_skeleton_dbus_interface_get_vtable (GDBusInterfaceSkeleton *skeleton)
{
  return (GDBusInterfaceVTable *) &_hs_session_skeleton_vtable;
}

static GVariant *
hs_session_skeleton_dbus_interface_get_properties (GDBusInterfaceSkeleton *_skeleton)
{
  HsSessionSkeleton *skeleton = HS_SESSION_SKELETON (_skeleton);

  GVariantBuilder builder;
  guint n;
  g_variant_builder_init (&builder, G_VARIANT_TYPE ("a{sv}"));
  if (_hs_session_interface_info.parent_struct.properties == NULL)
    goto out;
  for (n = 0; _hs_session_interface_info.parent_struct.properties[n] != NULL; n++)
    {
      GDBusPropertyInfo *info = _hs_session_interface_info.parent_struct.properties[n];
      if (info->flags & G_DBUS_PROPERTY_INFO_FLAGS_READABLE)
        {
          GVariant *value;
          value = _hs_session_skeleton_handle_get_property (g_dbus_interface_skeleton_get_connection (G_DBUS_INTERFACE_SKELETON (skeleton)), NULL, g_dbus_interface_skeleton_get_object_path (G_DBUS_INTERFACE_SKELETON (skeleton)), "org.home.hsession.Manager.Session", info->name, NULL, skeleton);
          if (value != NULL)
            {
              g_variant_take_ref (value);
              g_variant_builder_add (&builder, "{sv}", info->name, value);
              g_variant_unref (value);
            }
        }
    }
out:
  return g_variant_builder_end (&builder);
}

static void
hs_session_skeleton_dbus_interface_flush (GDBusInterfaceSkeleton *_skeleton)
{
}

static void hs_session_skeleton_iface_init (HsSessionIface *iface);
G_DEFINE_TYPE_WITH_CODE (HsSessionSkeleton, hs_session_skeleton, G_TYPE_DBUS_INTERFACE_SKELETON,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_SESSION, hs_session_skeleton_iface_init));

static void
hs_session_skeleton_finalize (GObject *object)
{
  HsSessionSkeleton *skeleton = HS_SESSION_SKELETON (object);
  g_list_free_full (skeleton->priv->changed_properties, (GDestroyNotify) _changed_property_free);
  if (skeleton->priv->changed_properties_idle_source != NULL)
    g_source_destroy (skeleton->priv->changed_properties_idle_source);
  g_main_context_unref (skeleton->priv->context);
  g_mutex_clear (&skeleton->priv->lock);
  G_OBJECT_CLASS (hs_session_skeleton_parent_class)->finalize (object);
}

static void
hs_session_skeleton_init (HsSessionSkeleton *skeleton)
{
  skeleton->priv = G_TYPE_INSTANCE_GET_PRIVATE (skeleton, HS_TYPE_SESSION_SKELETON, HsSessionSkeletonPrivate);
  g_mutex_init (&skeleton->priv->lock);
  skeleton->priv->context = g_main_context_ref_thread_default ();
}

static void
hs_session_skeleton_class_init (HsSessionSkeletonClass *klass)
{
  GObjectClass *gobject_class;
  GDBusInterfaceSkeletonClass *skeleton_class;

  g_type_class_add_private (klass, sizeof (HsSessionSkeletonPrivate));

  gobject_class = G_OBJECT_CLASS (klass);
  gobject_class->finalize = hs_session_skeleton_finalize;

  skeleton_class = G_DBUS_INTERFACE_SKELETON_CLASS (klass);
  skeleton_class->get_info = hs_session_skeleton_dbus_interface_get_info;
  skeleton_class->get_properties = hs_session_skeleton_dbus_interface_get_properties;
  skeleton_class->flush = hs_session_skeleton_dbus_interface_flush;
  skeleton_class->get_vtable = hs_session_skeleton_dbus_interface_get_vtable;
}

static void
hs_session_skeleton_iface_init (HsSessionIface *iface)
{
}

/**
 * hs_session_skeleton_new:
 *
 * Creates a skeleton object for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>.
 *
 * Returns: (transfer full) (type HsSessionSkeleton): The skeleton object.
 */
HsSession *
hs_session_skeleton_new (void)
{
  return HS_SESSION (g_object_new (HS_TYPE_SESSION_SKELETON, NULL));
}

/* ------------------------------------------------------------------------
 * Code for Object, ObjectProxy and ObjectSkeleton
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:HsObject
 * @title: HsObject
 * @short_description: Specialized GDBusObject types
 *
 * This section contains the #HsObject, #HsObjectProxy, and #HsObjectSkeleton types which make it easier to work with objects implementing generated types for D-Bus interfaces.
 */

/**
 * HsObject:
 *
 * The #HsObject type is a specialized container of interfaces.
 */

/**
 * HsObjectIface:
 * @parent_iface: The parent interface.
 *
 * Virtual table for the #HsObject interface.
 */

static void
hs_object_default_init (HsObjectIface *iface)
{
  /**
   * HsObject:power:
   *
   * The #HsPower instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("power", "power", "power", HS_TYPE_POWER, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

  /**
   * HsObject:session:
   *
   * The #HsSession instance corresponding to the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link>, if any.
   *
   * Connect to the #GObject::notify signal to get informed of property changes.
   */
  g_object_interface_install_property (iface, g_param_spec_object ("session", "session", "session", HS_TYPE_SESSION, G_PARAM_READWRITE|G_PARAM_STATIC_STRINGS));

}

typedef HsObjectIface HsObjectInterface;
G_DEFINE_INTERFACE_WITH_CODE (HsObject, hs_object, G_TYPE_OBJECT, g_type_interface_add_prerequisite (g_define_type_id, G_TYPE_DBUS_OBJECT));

/**
 * hs_object_get_power:
 * @object: A #HsObject.
 *
 * Gets the #HsPower instance for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link> on @object, if any.
 *
 * Returns: (transfer full): A #HsPower that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
HsPower *hs_object_get_power (HsObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Power");
  if (ret == NULL)
    return NULL;
  return HS_POWER (ret);
}

/**
 * hs_object_get_session:
 * @object: A #HsObject.
 *
 * Gets the #HsSession instance for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link> on @object, if any.
 *
 * Returns: (transfer full): A #HsSession that must be freed with g_object_unref() or %NULL if @object does not implement the interface.
 */
HsSession *hs_object_get_session (HsObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Session");
  if (ret == NULL)
    return NULL;
  return HS_SESSION (ret);
}


/**
 * hs_object_peek_power: (skip)
 * @object: A #HsObject.
 *
 * Like hs_object_get_power() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #HsPower or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
HsPower *hs_object_peek_power (HsObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Power");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return HS_POWER (ret);
}

/**
 * hs_object_peek_session: (skip)
 * @object: A #HsObject.
 *
 * Like hs_object_get_session() but doesn't increase the reference count on the returned object.
 *
 * <warning>It is not safe to use the returned object if you are on another thread than the one where the #GDBusObjectManagerClient or #GDBusObjectManagerServer for @object is running.</warning>
 *
 * Returns: (transfer none): A #HsSession or %NULL if @object does not implement the interface. Do not free the returned object, it is owned by @object.
 */
HsSession *hs_object_peek_session (HsObject *object)
{
  GDBusInterface *ret;
  ret = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Session");
  if (ret == NULL)
    return NULL;
  g_object_unref (ret);
  return HS_SESSION (ret);
}


static void
hs_object_notify (GDBusObject *object, GDBusInterface *interface)
{
  g_object_notify (G_OBJECT (object), ((_ExtendedGDBusInterfaceInfo *) g_dbus_interface_get_info (interface))->hyphen_name);
}

/**
 * HsObjectProxy:
 *
 * The #HsObjectProxy structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsObjectProxyClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsObjectProxy.
 */

static void
hs_object_proxy__hs_object_iface_init (HsObjectIface *iface)
{
}

static void
hs_object_proxy__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = hs_object_notify;
  iface->interface_removed = hs_object_notify;
}


G_DEFINE_TYPE_WITH_CODE (HsObjectProxy, hs_object_proxy, G_TYPE_DBUS_OBJECT_PROXY,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_OBJECT, hs_object_proxy__hs_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, hs_object_proxy__g_dbus_object_iface_init));

static void
hs_object_proxy_init (HsObjectProxy *object)
{
}

static void
hs_object_proxy_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
}

static void
hs_object_proxy_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  HsObjectProxy *object = HS_OBJECT_PROXY (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Power");
      g_value_take_object (value, interface);
      break;

    case 2:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Session");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
hs_object_proxy_class_init (HsObjectProxyClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = hs_object_proxy_set_property;
  gobject_class->get_property = hs_object_proxy_get_property;

  g_object_class_override_property (gobject_class, 1, "power");
  g_object_class_override_property (gobject_class, 2, "session");
}

/**
 * hs_object_proxy_new:
 * @connection: A #GDBusConnection.
 * @object_path: An object path.
 *
 * Creates a new proxy object.
 *
 * Returns: (transfer full): The proxy object.
 */
HsObjectProxy *
hs_object_proxy_new (GDBusConnection *connection,
  const gchar *object_path)
{
  g_return_val_if_fail (G_IS_DBUS_CONNECTION (connection), NULL);
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return HS_OBJECT_PROXY (g_object_new (HS_TYPE_OBJECT_PROXY, "g-connection", connection, "g-object-path", object_path, NULL));
}

/**
 * HsObjectSkeleton:
 *
 * The #HsObjectSkeleton structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsObjectSkeletonClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsObjectSkeleton.
 */

static void
hs_object_skeleton__hs_object_iface_init (HsObjectIface *iface)
{
}


static void
hs_object_skeleton__g_dbus_object_iface_init (GDBusObjectIface *iface)
{
  iface->interface_added = hs_object_notify;
  iface->interface_removed = hs_object_notify;
}

G_DEFINE_TYPE_WITH_CODE (HsObjectSkeleton, hs_object_skeleton, G_TYPE_DBUS_OBJECT_SKELETON,
                         G_IMPLEMENT_INTERFACE (HS_TYPE_OBJECT, hs_object_skeleton__hs_object_iface_init)
                         G_IMPLEMENT_INTERFACE (G_TYPE_DBUS_OBJECT, hs_object_skeleton__g_dbus_object_iface_init));

static void
hs_object_skeleton_init (HsObjectSkeleton *object)
{
}

static void
hs_object_skeleton_set_property (GObject      *gobject,
  guint         prop_id,
  const GValue *value,
  GParamSpec   *pspec)
{
  HsObjectSkeleton *object = HS_OBJECT_SKELETON (gobject);
  GDBusInterfaceSkeleton *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (HS_IS_POWER (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.home.hsession.Manager.Power");
        }
      break;

    case 2:
      interface = g_value_get_object (value);
      if (interface != NULL)
        {
          g_warn_if_fail (HS_IS_SESSION (interface));
          g_dbus_object_skeleton_add_interface (G_DBUS_OBJECT_SKELETON (object), interface);
        }
      else
        {
          g_dbus_object_skeleton_remove_interface_by_name (G_DBUS_OBJECT_SKELETON (object), "org.home.hsession.Manager.Session");
        }
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
hs_object_skeleton_get_property (GObject      *gobject,
  guint         prop_id,
  GValue       *value,
  GParamSpec   *pspec)
{
  HsObjectSkeleton *object = HS_OBJECT_SKELETON (gobject);
  GDBusInterface *interface;

  switch (prop_id)
    {
    case 1:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Power");
      g_value_take_object (value, interface);
      break;

    case 2:
      interface = g_dbus_object_get_interface (G_DBUS_OBJECT (object), "org.home.hsession.Manager.Session");
      g_value_take_object (value, interface);
      break;

    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (gobject, prop_id, pspec);
      break;
  }
}

static void
hs_object_skeleton_class_init (HsObjectSkeletonClass *klass)
{
  GObjectClass *gobject_class = G_OBJECT_CLASS (klass);

  gobject_class->set_property = hs_object_skeleton_set_property;
  gobject_class->get_property = hs_object_skeleton_get_property;

  g_object_class_override_property (gobject_class, 1, "power");
  g_object_class_override_property (gobject_class, 2, "session");
}

/**
 * hs_object_skeleton_new:
 * @object_path: An object path.
 *
 * Creates a new skeleton object.
 *
 * Returns: (transfer full): The skeleton object.
 */
HsObjectSkeleton *
hs_object_skeleton_new (const gchar *object_path)
{
  g_return_val_if_fail (g_variant_is_object_path (object_path), NULL);
  return HS_OBJECT_SKELETON (g_object_new (HS_TYPE_OBJECT_SKELETON, "g-object-path", object_path, NULL));
}

/**
 * hs_object_skeleton_set_power:
 * @object: A #HsObjectSkeleton.
 * @interface_: (allow-none): A #HsPower or %NULL to clear the interface.
 *
 * Sets the #HsPower instance for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Power.top_of_page">org.home.hsession.Manager.Power</link> on @object.
 */
void hs_object_skeleton_set_power (HsObjectSkeleton *object, HsPower *interface_)
{
  g_object_set (G_OBJECT (object), "power", interface_, NULL);
}

/**
 * hs_object_skeleton_set_session:
 * @object: A #HsObjectSkeleton.
 * @interface_: (allow-none): A #HsSession or %NULL to clear the interface.
 *
 * Sets the #HsSession instance for the D-Bus interface <link linkend="gdbus-interface-org-home-hsession-Manager-Session.top_of_page">org.home.hsession.Manager.Session</link> on @object.
 */
void hs_object_skeleton_set_session (HsObjectSkeleton *object, HsSession *interface_)
{
  g_object_set (G_OBJECT (object), "session", interface_, NULL);
}


/* ------------------------------------------------------------------------
 * Code for ObjectManager client
 * ------------------------------------------------------------------------
 */

/**
 * SECTION:HsObjectManagerClient
 * @title: HsObjectManagerClient
 * @short_description: Generated GDBusObjectManagerClient type
 *
 * This section contains a #GDBusObjectManagerClient that uses hs_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc.
 */

/**
 * HsObjectManagerClient:
 *
 * The #HsObjectManagerClient structure contains only private data and should only be accessed using the provided API.
 */

/**
 * HsObjectManagerClientClass:
 * @parent_class: The parent class.
 *
 * Class structure for #HsObjectManagerClient.
 */

G_DEFINE_TYPE (HsObjectManagerClient, hs_object_manager_client, G_TYPE_DBUS_OBJECT_MANAGER_CLIENT);

static void
hs_object_manager_client_init (HsObjectManagerClient *manager)
{
}

static void
hs_object_manager_client_class_init (HsObjectManagerClientClass *klass)
{
}

/**
 * hs_object_manager_client_get_proxy_type:
 * @manager: A #GDBusObjectManagerClient.
 * @object_path: The object path of the remote object (unused).
 * @interface_name: (allow-none): Interface name of the remote object or %NULL to get the object proxy #GType.
 * @user_data: User data (unused).
 *
 * A #GDBusProxyTypeFunc that maps @interface_name to the generated #GDBusObjectProxy<!-- -->- and #GDBusProxy<!-- -->-derived types.
 *
 * Returns: A #GDBusProxy<!-- -->-derived #GType if @interface_name is not %NULL, otherwise the #GType for #HsObjectProxy.
 */
GType
hs_object_manager_client_get_proxy_type (GDBusObjectManagerClient *manager, const gchar *object_path, const gchar *interface_name, gpointer user_data)
{
  static gsize once_init_value = 0;
  static GHashTable *lookup_hash;
  GType ret;

  if (interface_name == NULL)
    return HS_TYPE_OBJECT_PROXY;
  if (g_once_init_enter (&once_init_value))
    {
      lookup_hash = g_hash_table_new (g_str_hash, g_str_equal);
      g_hash_table_insert (lookup_hash, "org.home.hsession.Manager.Power", GSIZE_TO_POINTER (HS_TYPE_POWER_PROXY));
      g_hash_table_insert (lookup_hash, "org.home.hsession.Manager.Session", GSIZE_TO_POINTER (HS_TYPE_SESSION_PROXY));
      g_once_init_leave (&once_init_value, 1);
    }
  ret = (GType) GPOINTER_TO_SIZE (g_hash_table_lookup (lookup_hash, interface_name));
  if (ret == (GType) 0)
    ret = G_TYPE_DBUS_PROXY;
  return ret;
}

/**
 * hs_object_manager_client_new:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Asynchronously creates #GDBusObjectManagerClient using hs_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new() for more details.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_object_manager_client_new_finish() to get the result of the operation.
 *
 * See hs_object_manager_client_new_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_object_manager_client_new (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (HS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", hs_object_manager_client_get_proxy_type, NULL);
}

/**
 * hs_object_manager_client_new_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_object_manager_client_new().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_object_manager_client_new().
 *
 * Returns: (transfer full) (type HsObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
hs_object_manager_client_new_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * hs_object_manager_client_new_sync:
 * @connection: A #GDBusConnection.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: (allow-none): A bus name (well-known or unique) or %NULL if @connection is not a message bus connection.
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Synchronously creates #GDBusObjectManagerClient using hs_object_manager_client_get_proxy_type() as the #GDBusProxyTypeFunc. See g_dbus_object_manager_client_new_sync() for more details.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_object_manager_client_new() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
hs_object_manager_client_new_sync (
    GDBusConnection        *connection,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "connection", connection, "object-path", object_path, "get-proxy-type-func", hs_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


/**
 * hs_object_manager_client_new_for_bus:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @callback: A #GAsyncReadyCallback to call when the request is satisfied.
 * @user_data: User data to pass to @callback.
 *
 * Like hs_object_manager_client_new() but takes a #GBusType instead of a #GDBusConnection.
 *
 * When the operation is finished, @callback will be invoked in the <link linkend="g-main-context-push-thread-default">thread-default main loop</link> of the thread you are calling this method from.
 * You can then call hs_object_manager_client_new_for_bus_finish() to get the result of the operation.
 *
 * See hs_object_manager_client_new_for_bus_sync() for the synchronous, blocking version of this constructor.
 */
void
hs_object_manager_client_new_for_bus (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GAsyncReadyCallback     callback,
    gpointer                user_data)
{
  g_async_initable_new_async (HS_TYPE_OBJECT_MANAGER_CLIENT, G_PRIORITY_DEFAULT, cancellable, callback, user_data, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", hs_object_manager_client_get_proxy_type, NULL);
}

/**
 * hs_object_manager_client_new_for_bus_finish:
 * @res: The #GAsyncResult obtained from the #GAsyncReadyCallback passed to hs_object_manager_client_new_for_bus().
 * @error: Return location for error or %NULL
 *
 * Finishes an operation started with hs_object_manager_client_new_for_bus().
 *
 * Returns: (transfer full) (type HsObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
hs_object_manager_client_new_for_bus_finish (
    GAsyncResult        *res,
    GError             **error)
{
  GObject *ret;
  GObject *source_object;
  source_object = g_async_result_get_source_object (res);
  ret = g_async_initable_new_finish (G_ASYNC_INITABLE (source_object), res, error);
  g_object_unref (source_object);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}

/**
 * hs_object_manager_client_new_for_bus_sync:
 * @bus_type: A #GBusType.
 * @flags: Flags from the #GDBusObjectManagerClientFlags enumeration.
 * @name: A bus name (well-known or unique).
 * @object_path: An object path.
 * @cancellable: (allow-none): A #GCancellable or %NULL.
 * @error: Return location for error or %NULL
 *
 * Like hs_object_manager_client_new_sync() but takes a #GBusType instead of a #GDBusConnection.
 *
 * The calling thread is blocked until a reply is received.
 *
 * See hs_object_manager_client_new_for_bus() for the asynchronous version of this constructor.
 *
 * Returns: (transfer full) (type HsObjectManagerClient): The constructed object manager client or %NULL if @error is set.
 */
GDBusObjectManager *
hs_object_manager_client_new_for_bus_sync (
    GBusType                bus_type,
    GDBusObjectManagerClientFlags  flags,
    const gchar            *name,
    const gchar            *object_path,
    GCancellable           *cancellable,
    GError                **error)
{
  GInitable *ret;
  ret = g_initable_new (HS_TYPE_OBJECT_MANAGER_CLIENT, cancellable, error, "flags", flags, "name", name, "bus-type", bus_type, "object-path", object_path, "get-proxy-type-func", hs_object_manager_client_get_proxy_type, NULL);
  if (ret != NULL)
    return G_DBUS_OBJECT_MANAGER (ret);
  else
    return NULL;
}


