cc = gcc
all: a.out
a.out: b.c data.c data.h
	$(cc) b.c data.c `pkg-config --cflags --libs gio-2.0`
b.c: a.c
	grep -v "register" a.c > b.c
data.c:
	glib-compile-resources data.gresource.xml --generate-source
data.h:
	glib-compile-resources data.gresource.xml --target data.h --generate-header
clean:
	rm b.c a.out data.[ch]

